INSERT INTO Recommendation (text) VALUES
('Do not go to school, work, a childcare center or any other public space.'),
('Do not use public transport.'),
('If the sick person lives alone and has no help to get essentials such as food or medication, use phone/online grocery and pharmacy home delivery services.'),
('Do not receive visitors at home.'),
('If the sick person lives with other people who are not infected by COVID-19:<ul><li>remain alone in one room of the house as often as possible and close to the door.</li><li>eat and sleep alone in one room of the house.</li><li>if possible, use a bathroom reserved for the sick person sole use. Otherwise, disinfect the bathroom after every use.</li><li>avoid as much as possible contact with other people in the home. If this is impossible, wear a mask. If a mask is not available, stay at least two meters away from other people.</li></ul>'),
('Open a window to air out the sick person\'s room and home often \(weather permitting\).'),
('Do not go to a medical clinic unless you have first obtained an appointment and have notified the clinic that you have COVID-19. If you need to go to the emergency room \(eg, if you have difficulty breathing\), contact 911 and tell the person that you are sick with COVID-19.'),
('Wear a mask when someone is in the same room as you.'),
('Wear a mask if you must leave your home to seek medical care, you must first notify the medical clinic \(or 911, if it is an emergency\) that you have COVID-19.'),
('If you need to cough, sneeze, or blow your nose:<ul><li>If you have a disposable tissue use it to cough, sneeze or blow your nose then discard the tissue in the garbage, and then wash your hands with soap and water.</li><li>If you do not have disposable tissues, cough, or sneeze in the crook of your arm.</li></ul>'),
('Wash your hands:<ul><li>Wash your hands often with soap under warm running water for at least 20 seconds.</li><li>Use an alcohol- based hand rub if soap and water are not available.</li><li>Wash your hands before eating and whenever your hands look dirty.</li><li>After using the toilet, put the lid down before flushing and then wash your hands.</li></ul>'),
('Do not share plates, utensils, glasses, towels, bed sheets or clothes with others.'),
('Watch your symptoms and take your temperature every day: <ul><li>Take your temperature every day at the same hour.</li><li>If you are taking medication for fever wait at least four hours before taking your temperature.</li></ul>'),
('Directives in case of severe symptoms:<ul><li>If your symptoms worsen call 514-644-4545 or call your doctor.</li><li>If you have difficulty breathing, or shortness of breath or chest pain call 911 and inform them you may be infected by COVID-19.</li></ul>'),
('If someone close or caregiver helps you with your daily activities, then before helping you, the person must wash his/her hand, wear a mask and put-on disposable gloves. After helping you, the person must take off the gloves and put them in a garbage bin with a lid, wash his/her hands, take off the mask and put it in a garbage bin with a lid, and wash his/her hands again.'),
('For help with psychosocial matters, contact 811.');